apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      role: backend
  minReadySeconds: 20  # Moved outside of selector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend-container
        image: proyecto
        ports:
        - containerPort: 3001
